:package:  Server object architecture
epitech-mirroring/Zappy pull request #31
Opened 2024-06-03 13:14 UTC by 6im0n

# 📝 Description
Add object architecture for the server

2024-06-03 14:21 UTC, BxptisteM approved these changes
Seems good for me (just fix the linter errors)

2024-06-03 15:02 UTC, RenardFute requested changes
Please fix the indentation and what I've pointed out.
I will make a deeper review on the real logic once this is all cleared-out.

2024-06-06 13:33 UTC, Klayni approved these changes

2024-06-08 10:40 UTC, RenardFute approved these changes
Seems fine to me, however I feel like the arrays and buffer types would have benefited from unit tests (their behaviors are quite simple to anticipate)

2024-06-09 15:17 UTC, BxptisteM approved these changes

2024-06-09 21:40 UTC, Klayni approved these changes

2024-06-10 16:42 UTC, merged