✨ Gui - World Implementation
epitech-mirroring/Zappy pull request #32
Opened 2024-06-03 14:25 UTC by BxptisteM

# Implementation of the GUI World class :

- Added a Position class (usefull to manipulate the positions of the objects)
- Fixed the object class to make it use the position class
- Added the world class with his methods
- Added tests

2024-06-03 14:47 UTC, RenardFute requested changes
I feel like your include could use non-relative paths, since everything should be synced by the CMake. Otherwise, this seems nice to me, I just a constructor that accepts a position for every object and defaults it to 0, 0 would have been better since with the current system if you want to create an object at x, y it would take you 3 or more lines.

Fix the indentation error and ask me back ^^

2024-06-03 14:47 UTC, RenardFute commented on gui/src/position/Position.cpp
> +Position::~Position()
could have been ``= default``

2024-06-03 14:47 UTC, RenardFute commented on gui/src/world/World.hpp
> +#define WORLD_HPP_
Missing indentation 👀

2024-06-03 15:06 UTC, RenardFute approved these changes

2024-06-03 17:43 UTC, 6im0n approved these changes
good for me :+1:

2024-06-04 15:53 UTC, BxptisteM commented on gui/src/objects/eggs/Egg.cpp
> +Egg::Egg(std::string teamName, int ownerID, Position tile)
This is the ID of the trantorian who laid the egg (I think we should display it when we click on the egg)

2024-06-04 16:56 UTC, BxptisteM commented on tests/gui/get_objects_positions_spec.cpp
I named my test files following the casing of the templates ones that where here at the very begining that's why but it's now fixed 🙂

2024-06-05 12:21 UTC, Quentintnrl commented on gui/src/objects/eggs/Egg.cpp
> +Egg::Egg(std::string teamName, int ownerID, Position tile)
We don't stock this data on the server

2024-06-05 12:27 UTC, merged